name: sum_cap
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  awesome_snackbar_content: ^0.1.1
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_audio_waveforms: ^1.2.1+8
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.10
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  http: ^1.2.0
  intl: ^0.19.0
  just_audio: ^0.9.36
  path: ^1.8.3
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
