name: sum_cap
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  audioplayers: ^5.2.1
  awesome_snackbar_content: ^0.1.3
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_audio_waveforms: ^1.2.1+8
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  flutter_sound: ^9.2.13
  # font_awesome_flutter: ^10.7.0
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  google_generative_ai: ^0.2.2
  http: any
  # intl: ^0.19.0
  intl: ^0.18.1
  just_audio: ^0.9.36
  path: any
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  record: ^5.0.4
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  translator: ^1.0.0
  url_launcher: ^6.2.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
